// <auto-generated />
using System;
using CakeZone.Services.Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CakeZone.Services.Inventory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240619124403_InitialModel")]
    partial class InitialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CakeZone.Services.Inventory.Model.Inventory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StorageDepotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AverageDemand")
                        .HasColumnType("int");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<int>("Demand")
                        .HasColumnType("int");

                    b.Property<decimal>("HoldingCostPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InventoryPosition")
                        .HasColumnType("int");

                    b.Property<int>("LeadTime")
                        .HasColumnType("int");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinLevel")
                        .HasColumnType("int");

                    b.Property<int?>("OrderFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("OrderQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("OrderingCostPerOrder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OrdersOutstanding")
                        .HasColumnType("int");

                    b.Property<decimal>("ShortageCostPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StandardDeviationDemand")
                        .HasColumnType("int");

                    b.Property<int?>("UnitsShort")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "StorageDepotId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("CakeZone.Services.Inventory.Model.StockIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("Storage_DepotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Storage_DepotId");

                    b.HasIndex("ProductId", "Storage_DepotId");

                    b.ToTable("StockIssue");
                });

            modelBuilder.Entity("CakeZone.Services.Inventory.Model.StockReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StorageDepotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Storage_DepotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Storage_DepotId");

                    b.HasIndex("SupplierId");

                    b.ToTable("StockReceipt");
                });

            modelBuilder.Entity("CakeZone.Services.Inventory.Model.Storage_Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Storage_Depot");
                });

            modelBuilder.Entity("CakeZone.Services.Inventory.Model.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("CakeZone.Services.Inventory.Model.StockIssue", b =>
                {
                    b.HasOne("CakeZone.Services.Inventory.Model.Storage_Depot", "Storage_Depot")
                        .WithMany()
                        .HasForeignKey("Storage_DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CakeZone.Services.Inventory.Model.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("ProductId", "Storage_DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Storage_Depot");
                });

            modelBuilder.Entity("CakeZone.Services.Inventory.Model.StockReceipt", b =>
                {
                    b.HasOne("CakeZone.Services.Inventory.Model.Storage_Depot", "Storage_Depot")
                        .WithMany()
                        .HasForeignKey("Storage_DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CakeZone.Services.Inventory.Model.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storage_Depot");

                    b.Navigation("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
